### ISSUE TITLE
Encrypt and sign one pass

### ISSUE THREAD

**Issue by Keglerz** [hapheus/n8n-nodes-pgp#1]
Is there any way to encrypt and sign in one pass? Instead of encrypt first then sign using another node

**Comment by hapheus** [comment]
Thank you for your feedback! Currently, encrypting and signing can't be done in one step, but we're open to adding this feature.

**Comment by hapheus** [comment]
<img width="937" alt="image" src="https://github.com/user-attachments/assets/e34005a0-871d-46b8-9503-1c94a9498631">
👍

**Comment by Keglerz** [comment]
Thanks! 🙏

**Comment by Keglerz** [comment]
Hi, is the new feature, encrypt or sign first? the final output is signature?

**Comment by hapheus** [comment]
In the latest version, I had to remove the combined Encrypt/Sign and Decrypt/Verify operations.

The reason is:

- Encryption typically uses the recipient's public key.
- Signing usually requires the sender's private key.
- Decryption is done by the recipient with their private key.
- Verification is performed by the recipient using the sender's public key.
- This process involves two separate key pairs.

Currently, there’s no straightforward way to represent two separate credentials in the node (or the necessary description for it is missing).

**Comment by erictmnz** [comment]
Just a clarification:
Currently the credential has a passphrase, public key and a private key field.
Would that not be all that's needed for encrypt, compress and sign in a single pass?
As you said one would put into credential 1:
- the recipients public key for encryption in public key and 
- the senders private key for signing as private key.
Use the encrypt & sign node to generate the file to share with the other party (having received the public key from them and shared the signing public key with them).

When receiving a file we would put into credential 2:
- separate senders public key to verify (what they encrypted with their private key) in the public key
- separate recipients private key to decrypt (what the sender encrypted with their public key)
Use the verify & decrypt node to decrypt the file shared from the other party (having received their public key to verify and shared a public key to encrypt).

So encrypt & sign and verify & decrypt would be done with separate credential sets.
I might be missing something but I think that should work?

I attached a diagram to show the scenario if both sender and receiver were using n8n to exchange encrypted files.
![image](https://github.com/user-attachments/assets/1127e7fe-7594-4ae0-82c6-b352a07b5eb2)

**Comment by hapheus** [comment]
Yes, that should work. I honestly never considered mixing private and public keys from different accounts in the credentials. As long as the number of clients remains manageable or the private key doesn't change, it shouldn't be a problem. I'll go ahead and implement this approach.

**Comment by hapheus** [comment]
Just released a new version that reintroduces support for the combined operations `Encrypt-And-Sign` and `Decrypt-And-Verify`.
